[package]
name = "CashTradingGame"
version = "1.0.0"
authors = ["Cash Trading Game Team"]

[addresses]
cash_trading_game = "0x37691b1a87e7d1054007c5687424ef10438993722925b189c09f1bc7fe172ac5"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]