[package]
name = "CashTradingGame"
version = "1.0.0"
authors = ["Cash Trading Game Team"]

[addresses]
cash_trading_game = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.21"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

[move]
compiler-version = "2.0"
